# frozen_string_literal: true

source 'https://rubygems.org'

# 既存のGem...

# PDFファイルの読み取り
gem 'pdf-reader'

# GEMINIクライアント
gem 'google-cloud-ai-generative'

# ファイル処理
gem 'mini_magick'

# CORS対応
gem 'rack-cors'