"""add_question_text_to_interview_responses

Revision ID: feb04ca3cafb
Revises: f562b41918cd
Create Date: 2024-12-12 11:49:37.158887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb04ca3cafb'
down_revision: Union[str, None] = 'f562b41918cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_questions', 'job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('base_questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('base_questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_base_questions_id'), 'base_questions', ['id'], unique=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.alter_column('custom_questions', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('custom_questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_custom_questions_id'), 'custom_questions', ['id'], unique=False)
    op.add_column('interview_responses', sa.Column('question_text', sa.String(), nullable=True))
    op.add_column('interview_responses', sa.Column('answer_text', sa.String(), nullable=True))
    op.add_column('interview_responses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('interview_responses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('interview_responses', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interview_responses', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interview_responses', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_interview_responses_id'), 'interview_responses', ['id'], unique=False)
    op.drop_column('interview_responses', 'response_text')
    op.drop_column('interview_responses', 'response_time')
    op.alter_column('interviews', 'job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('interviews', 'candidate_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interviews', 'candidate_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interviews', 'interview_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('interviews', 'avatar_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'hayato'::character varying"))
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_unique_constraint(None, 'interviews', ['interview_url'])
    op.alter_column('job_postings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_postings', 'requirements',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_companyuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'is_companyuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.alter_column('job_postings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_postings', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'requirements',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_postings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('job_postings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'interviews', type_='unique')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.alter_column('interviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interviews', 'avatar_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'hayato'::character varying"))
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('interviews', 'interview_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'candidate_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'candidate_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('interview_responses', sa.Column('response_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('interview_responses', sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_interview_responses_id'), table_name='interview_responses')
    op.alter_column('interview_responses', 'question_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interview_responses', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('interview_responses', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('interview_responses', 'updated_at')
    op.drop_column('interview_responses', 'created_at')
    op.drop_column('interview_responses', 'answer_text')
    op.drop_column('interview_responses', 'question_text')
    op.drop_index(op.f('ix_custom_questions_id'), table_name='custom_questions')
    op.alter_column('custom_questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('custom_questions', 'interview_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_base_questions_id'), table_name='base_questions')
    op.alter_column('base_questions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('base_questions', 'question_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('base_questions', 'job_posting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
